name: Minute Cleanup

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute

jobs:
  cleanup:  # Job name with a colon
  runs-on: ubuntu-latest

    steps:

      - name: Cleanup task
        run: echo "Performing cleanup every minute"

