name: Minute Job

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every minute

jobs:
  run-every-minute:
    runs-on: ubuntu-latest

    steps:
      - name: Print Current Time
        run: echo "The current time is $(date)"


