name: Minute Cleanup

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run cleanup script
        run: echo "Performing cleanup every minute!"